name: Build and Push to Harbor

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    env:
      DEFAULT_BRANCH: main
      BETA_BRANCH: develop

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Harbor
        env:
          HARBOR_HOST: ${{ secrets.HARBOR_HOST }}
          HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
          HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
        run: |
          set -euo pipefail
          echo "${HARBOR_PASSWORD}" | docker login "${HARBOR_HOST}" -u "${HARBOR_USERNAME}" --password-stdin

      - name: Build and push image
        env:
          HARBOR_HOST: ${{ secrets.HARBOR_HOST }}
          HARBOR_PROJECT: ${{ secrets.HARBOR_PROJECT }}
          HARBOR_REPOSITORY: ${{ secrets.HARBOR_REPOSITORY }}
        run: |
          set -euo pipefail
          REF="${GITHUB_REF:-}"
          SHORT_SHA="$(echo "${GITHUB_SHA:-unknown}" | cut -c1-7)"
          IS_TAG=false
          TAG_NAME=""

          if [[ "${REF}" == refs/tags/* ]]; then
            IS_TAG=true
            TAG_NAME="${GITHUB_REF_NAME}"
            BRANCH="${DEFAULT_BRANCH}"
          else
            BRANCH="${GITHUB_REF_NAME:-${DEFAULT_BRANCH}}"
          fi

          IMAGE="${HARBOR_HOST}/${HARBOR_PROJECT}/${HARBOR_REPOSITORY:-calcard}"

          TAG_ARGS=(
            -t "${IMAGE}:${BRANCH}-${SHORT_SHA}"
          )

          # Tag special channels
          if [ "${BRANCH}" = "${DEFAULT_BRANCH}" ]; then
            TAG_ARGS+=(-t "${IMAGE}:latest")
          elif [ "${BRANCH}" = "${BETA_BRANCH}" ]; then
            TAG_ARGS+=(-t "${IMAGE}:beta")
          fi

          if [ "${IS_TAG}" = true ] && [ -n "${TAG_NAME}" ]; then
            TAG_ARGS+=(-t "${IMAGE}:${TAG_NAME}")
          fi

          PRIMARY_TAG="${IMAGE}:${BRANCH}-${SHORT_SHA}"
          echo "PRIMARY_TAG=${PRIMARY_TAG}" >> "${GITHUB_ENV}"
          echo "IMAGE=${IMAGE}" >> "${GITHUB_ENV}"

          docker buildx build \
            --platform linux/amd64 \
            "${TAG_ARGS[@]}" \
            --push .

      - name: Extract calcard binary
        run: |
          set -euo pipefail
          mkdir -p artifacts
          docker pull "${PRIMARY_TAG}"
          CID="$(docker create "${PRIMARY_TAG}")"
          docker cp "${CID}:/calcard" artifacts/calcard
          docker rm "${CID}"
          ls -lh artifacts

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: calcard-${{ github.ref_name || env.DEFAULT_BRANCH }}
          path: artifacts/calcard

      - name: Publish binary to Gitea Packages (tags only)
        if: startsWith(github.ref, 'refs/tags/')
        env:
          PACKAGE_OWNER: ${{ github.repository_owner }}
          PACKAGE_NAME: calcard
          TAG_NAME: ${{ github.ref_name }}
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
          GITEA_SERVER_URL: ${{ github.server_url }}
        run: |
          set -euo pipefail
          if [ ! -f artifacts/calcard ]; then
            echo "calcard binary missing" >&2
            exit 1
          fi

          DEST_URL="${GITEA_SERVER_URL}/api/packages/${PACKAGE_OWNER}/generic/${PACKAGE_NAME}/${TAG_NAME}/calcard"
          curl -f -X PUT \
            -H "Authorization: token ${GITEA_TOKEN}" \
            -T artifacts/calcard \
            "${DEST_URL}"
