{{- $name := default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- $fullname := (default $name .Values.fullnameOverride) | trunc 63 | trimSuffix "-" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-secret
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  {{ if not .Values.app.oauth.clientSecretExistingSecret.name }}
  APP_OAUTH_CLIENT_SECRET: {{ .Values.app.oauth.clientSecret | quote }}
  {{ end }}
  {{ if not .Values.app.sessionSecretExistingSecret.name }}
  APP_SESSION_SECRET: {{ .Values.app.sessionSecret | quote }}
  {{ end }}
